# Generated by Django 5.2 on 2025-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploder', '0002_image_description_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
